// =========================================================
// Healthy Store - Single Source of Truth (Data-Driven)
// عدّل التصنيفات والمنتجات هنا فقط
// =========================================================

window.HS_DATA = {
  categories: [
    { label: "الدقيق والحبوب", value: "الدقيق والحبوب" },
    { label: "🍜 الاندومي", value: "الاندومي" },
    { label: "🍝 المكرونات", value: "المكرونات" },
    { label: "🥖 المخبوزات", value: "المخبوزات" },
    { label: "🍪 البسكويت والحلويات", value: "البسكويت والحلويات" },
    { label: "🥣 الكورن فليكس", value: "الكورن فليكس" },
    { label: "🥨 الشيبسي والسناك", value: "الشيبسي والسناك" },
    { label: "🍚 الأرز والشوفان", value: "الأرز والشوفان" },
    { label: "🍰 الكيك", value: "الكيك" },
    { label: "🍯 الصلصات والصوصات", value: "الصلصات" },
    { label: "البذور والتوابل", value: "البذور والتوابل" },
  ],
  products: [
    {
      id: 1,
      name: " Ganachti زبده لوز",
      price: 150,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "زبده لوز بدون اي اضافات",
      image: "Gemini_Generated_Image_68hmb868hmb868hm.png",
      tags: ["Ganachti", "بدون اي اضافات"],
    },
    {
      id: 2,
      name: " Ganachti زبده الفول السوداني",
      price: 65,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "70 جم",
      ingredients: "زبده فول سوداني بدون اي اضافات",
      image: "Gemini_Generated_Image_v6uerdv6uerdv6ue.png",
      tags: ["Ganachti", "بدون اي اضافات "],
    },
    {
      id: 3,
      name: "chocolate spread Box",
      price: 225,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "زيت جوز هند طبيعي ، دقيق ارز، نشأ ارز استيفيا +ايرثريتول ، كاكاو طبيعي، ليسيثين دوار الشمس",
      image: "Gemini_Generated_Image_y83wc0y83wc0y83w.png",
      tags: ["كاكاو طبيعي"],
    },
    {
      id: 4,
      name: "light dark chocolate",
      price: 45,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "40 جم",
      ingredients: "زبدة كاكاو طبيعي، دقيق ارز، نشأ ارز، استيفيا+ايرثريتول، مسحوق الكاكاو الطبيعي، ليسيتين دوار الشمس",
      image: "Gemini_Generated_Image_9gs53i9gs53i9gs5.png",
      tags: ["Ganachti", "كاكاو طبيعي", "خالي جلوتين", "خالي بيض", "خالي لبن ومكسرات ", "خالي سكر", "خالي صويا", "سيامي نباتي"],
    },
    {
      id: 5,
      name: " Ganachti اسبريد ساده استيفيا",
      price: 120,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "زيت جوز هند طبيعي، دقيق ارز، نشا ارز استيفيا +ايرثريتول، كاكاو طبيعي، ليسيثين دوار الشمس ",
      image: "Gemini_Generated_Image_d1jid4d1jid4d1ji.png",
      tags: ["Ganachti", "كاكاو طبيعي", "خالي جلوتين", "خالي بيض", "خالي لبن ومكسرات ", "خالي سكر", "خالي صويا"],
    },
    {
      id: 6,
      name: "اسبريد بندق استيفيا",
      price: 135,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "350 جم",
      ingredients: "زيت جوز هند طبيعي,بندق طبيعي، دقيق ارز «نشأ ارز استيفيا +ايرثريتول، كاكاو، طبيعي، ليسيثين دوار الشمس",
      image: "Gemini_Generated_Image_o73zgdo73zgdo73z.png",
      tags: ["Ganachti", "كاكاو طبيعي", "خالي جلوتين", "خالي بيض", "خالي لبن ومكسرات ", "خالي سكر", "خالي صويا"],
    },
    {
      id: 7,
      name: "Smoked BBQ chips",
      price: 15,
      currency: "ج.م",
      category: "الشيبسي والسناك",
      weight: " جم",
      ingredients: "",
      image: "WhatsApp Image 2026-02-15 at 4.05.29 PM.jpeg",
      tags: ["Gluten-free"],
    },
    {
      id: 8,
      name: "زعتر بري",
      price: 55,
      currency: "ج.م",
      category: "البذور والتوابل",
      weight: "30 جم",
      ingredients: "",
      image: "WhatsApp Image 2026-03-05 at 11.36.11 PM.jpeg",
      tags: ["100% Natural"],
    },
    {
      id: 9,
      name: "بذور اليقطين",
      price: 155,
      currency: "ج.م",
      category: "البذور والتوابل",
      weight: "200 جم",
      ingredients: "",
      image: "WhatsApp Image 2026-03-05 at 11.32.34 PM.jpeg",
      tags: ["100% Natural", "Gluten free", "Vegan"],
    },
    {
      id: 10,
      name: "Vanilla powder Greens",
      price: 85,
      currency: "ج.م",
      category: "الصلصات",
      weight: "60 جم",
      ingredients: "",
      image: "WhatsApp Image 2026-03-10 at 3.28.11 PM.jpeg",
      tags: ["No Added Sugar"],
    },
    {
      id: 10,
      name: "بذور عباد الشمس",
      price: 125,
      currency: "ج.م",
      category: "البذور والتوابل",
      weight: "200 جم",
      ingredients: "",
      image: "WhatsApp Image 2026-03-05 at 11.32.32 PM.jpeg",
      tags: ["100% Natural"],
    },
    {
      id: 11,
      name: "Healthy BBQ Sauce Zero treat ",
      price: 145,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.47 PM.jpeg",
      tags: ["Gluten-free", "GMO-free", "Lactose-free", "Fat-free", "Keto-friendly", "Vegan", "Zero added sugar"],
    },
    {
      id: 12,
      name: "Healthy Tasty Sauce Zero treat ",
      price: 150,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.56 PM.jpeg",
      tags: ["Gluten-free"],
    },
    {
      id: 13,
      name: "Healthy Salted Caramel Sauce Zero treat ",
      price: 175,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.56 PM (1).jpeg",
      tags: ["Gluten-free", "GMO-free", "Fat-free", "Keto-friendly", "Zero added sugar"],
    },
    {
      id: 14,
      name: "Healthy Chocolate Sauce Zero treat",
      price: 175,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.57 PM.jpeg",
      tags: ["Gluten-free", "GMO-free", "Fat-free", "Keto-friendly", "Zero added sugar"],
    },
    {
      id: 15,
      name: "Healthy Sweet Chili Sauce Zero treat",
      price: 140,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.57 PM (1).jpeg",
      tags: ["Gluten-free", "GMO-free", "Lactose-free", "Fat-free", "Keto-friendly", "Vegan", "Zero added sug"],
    },
    {
      id: 16,
      name: "Healthy Ketchup Sauce Zero treat",
      price: 140,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.58 PM.jpeg",
      tags: ["Gluten-free", "GMO-free", "Lactose-free", "Fat-free", "Keto-friendly", "Vegan", "Zero added sug"],
    },
    {
      id: 17,
      name: "Healthy Strawbeery Sauce Zero treat",
      price: 140,
      currency: "ج.م",
      category: "الصلصات",
      weight: "300 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-06 at 12.15.58 PM (1).jpeg",
      tags: ["Gluten-free", "GMO-free", "Fat-free", "Keto-friendly", "Zero added sugar"],
    },
    {
      id: 18,
      name: " Healthy STRAWBERRY Fruit Pureé Zero treat",
      price: 100,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "300 جم",
      ingredients: null,
      image: "Gemini_Generated_Image_f6q2a5f6q2a5f6q2.png",
      tags: ["No Added Sugar"],
    },
    {
      id: 19,
      name: " Healthy Mango fruit Zero treat",
      price: 120,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "180 جم",
      ingredients: null,
      image: "Gemini_Generated_Image_jf2o03jf2o03jf2o.png",
      tags: ["No Added Sugar"],
    },
    {
      id: 20,
      name: "Healthy mixed berries Zero treat",
      price: 150,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "180 جم",
      ingredients: null,
      image: "Gemini_Generated_Image_y9j58cy9j58cy9j5.png",
      tags: ["No Added Sugar"],
    },
    {
      id: 21,
      name: "natulesta BBQ Sauce",
      price: 115,
      currency: "ج.م",
      category: "الصلصات",
      weight: "355 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-05 at 11.33.26 PM.jpeg",
      tags: ["Gluten-free", "low Cal", "Fat-free", "Keto-friendly"],
    },
    {
      id: 22,
      name: "natulesta Ketchup Sauce",
      price: 110,
      currency: "ج.م",
      category: "الصلصات",
      weight: "355 جم",
      ingredients: null,
      image: "WhatsApp Image 2026-03-05 at 11.32.57 PM.jpeg",
      tags: ["Gluten-free", "low Cal", "Fat-free", "Keto-friendly", "Vegan"],
    },
    {
      id: 23,
      name: "Corn pasta مكرونه قلم",
      price: 45,
      currency: "ج.م",
      category: "المكرونات",
      weight: "350 جم",
      ingredients: "ارز + ذره",
      image: "Gemini_Generated_Image_sdjimtsdjimtsdji.png",
      tags: ["Gluten-free"],
    },
    {
      id: 24,
      name: "Corn pasta",
      price: 45,
      currency: "ج.م",
      category: "المكرونات",
      weight: "350 جم",
      ingredients: "ارز + ذره",
      image: "Gemini_Generated_Image_sf83hmsf83hmsf83.png",
      tags: ["Gluten-free"],
    },
    {
      id: 25,
      name: "Corn pasta لسان عصفور",
      price: 45,
      currency: "ج.م",
      category: "المكرونات",
      weight: "350 جم",
      ingredients: "ارز+ذره",
      image: "Gemini_Generated_Image_aoocdwaoocdwaooc.png",
      tags: ["Gluten-free"],
    },
    {
      id: 26,
      name: "Rice pasta لسان عصفور",
      price: 45,
      currency: "ج.م",
      category: "المكرونات",
      weight: "350 جم",
      ingredients: "ارز+ذره",
      image: "Gemini_Generated_Image_a5lyr6a5lyr6a5ly.png",
      tags: ["Gluten-free"],
    },
    {
      id: 27,
      name: "Rice pasta مكرونه قلم",
      price: 45,
      currency: "ج.م",
      category: "المكرونات",
      weight: "350 جم",
      ingredients: "ارز+ذره",
      image: "Gemini_Generated_Image_uau2hiuau2hiuau2.png",
      tags: ["Gluten-free", "Wheat-free", "Dairy-free", "Egg-free", "Corn-free"],
    },
    {
      id: 28,
      name: "Choco target ligth dark chocolate",
      price: 125,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "150 جم",
      ingredients: "سكر - زبدة كاكاو طبيعي - نشاء أرز(دقيق أرز) - كتلة الكاكاو الطبيعى - ليسيثين دوار الشمس ",
      image: "Gemini_Generated_Image_shs20qshs20qshs2.png",
      tags: ["Gluten-free", "soya free", "Dairy-free", "Egg-free", "nuts-free", "vanillia free"],
    },
    {
      id: 29,
      name: " Ciocko Sticks Schar",
      price: "غير متوفر حاليا",
      currency: "",
      category: "البسكويت والحلويات",
      weight: "150 جم",
      ingredients: " شوكولاتة بالحليب ٤٦٪ (سكر، كتلة الكاكاو*، زبدة الكاكاو*، مسحوق حليب كامل الدسم، مستحلب: ليسيثين؛ نكهة طبيعية)، نشا الذرة، نشا التابيوكا، نشا الذرة، سكر، زيت النخيل، شراب الجلوكوز، مُكثِّف: صمغ الغوار؛ ملح، مستحلب: ليسيثين بذور اللفت؛ عوامل رفع: كربونات الصوديوم، كربونات الأمونيوم؛ قد تحتوي على آثار من البيض والمكسرات (اللوز والبندق). خالية من القمح",
      image: "تصميم بدون عنوان.png",
      tags: ["Gluten-free"],
    },
    {
      id: 30,
      name: "Vanilla Creams Sugar Free Schar",
      price: "غير متوفر حاليا",
      currency: "",
      category: "البسكويت والحلويات",
      weight: "115 جم",
      ingredients: "بسكويت مقرمش بحشوة فانيليا كريمية. بدون إضافة سكر، لكنه غني بالنكهة. مثالي مع الشاي أو القهوة، أو كوجبة خفيفة بين الوجبات!",
      image: "تصميم بدون عنوان (3).png",
      tags: ["Gluten-free", "suggar free"],
    },
    {
      id: 31,
      name: "Digerstive Schar",
      price: 220,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "150 جم",
      ingredients: " مشروبات دايجستف يومية مصنوعة من الحنطة السوداء الطبيعية، لا تتنازل عن النكهة. الخيار الأمثل لراحة صحية أثناء استراحة القهوة.",
      image: "تصميم بدون عنوان (2).png",
      tags: ["Gluten-free", "Dairy-free"],
    },
    {
      id: 32,
      name: "Marshzone marshmallows green apple flavor",
      price: 7,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_qge3shqge3shqge3.png",
      tags: ["Gluten-free"],
    },
    {
      id: 33,
      name: "Marshzone marshmallows Strawberry flavor",
      price: 7,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "20 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_ebzvloebzvloebzv.png",
      tags: ["Gluten-free"],
    },
    {
      id: 34,
      name: "Marshzone marshmallows Grape flavor",
      price: 7,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "20 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_isx80xisx80xisx8.png",
      tags: ["Gluten-free"],
    },
    {
      id: 35,
      name: "Marshzone marshmallows banana flavor",
      price: 7,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "20 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_eqq74eeqq74eeqq7.png",
      tags: ["Gluten-free"],
    },
    {
      id: 36,
      name: "CHOCO CRISPIES",
      price: 570,
      currency: "ج.م",
      category: "الكورن فليكس",
      weight: "300 g",
      ingredients: "",
      image: "WhatsApp Image 2026-03-06 at 2.32.28 AM.jpeg",
      tags: ["Gluten-free", " Corn free", "milk free", "wheat free"],
    },
    {
      id: 37,
      name: "Apple cider vinegar",
      price: 580,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "473 ml",
      ingredients: "",
      image: "Gemini_Generated_Image_ye0st5ye0st5ye0s.png",
      tags: ["Gluten-free"],
    },
    {
      id: 38,
      name: "Rice paper",
      price: 230,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "340 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_kvm39mkvm39mkvm3.png",
      tags: ["Gluten-free"],
    },
    {
      id: 39,
      name: "دقيق الشوفان",
      price: 120,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: " 500 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_vsnls5vsnls5vsnl.png",
      tags: ["Gluten-free"],
    },
    {
      id: 40,
      name: "Crackers al rosmarino",
      price: 0,
      currency: "ج.م",
      category: "الشيبسي والسناك",
      weight: "210 جم",
      ingredients: "استمتع بهذه المقرمشات الخفيفة والهشة كوجبة خفيفة بعد الظهر أو مع مشروبك قبل العشاء. مصنوعة من إكليل الجبل الطبيعي لنكهة متوسطية غنية، ومعبأة في عبوات قابلة لإعادة الإغلاق لتستمتع بها في أي مكان وزمان.",
      image: "Gemini_Generated_Image_vugtbmvugtbmvugt.png",
      tags: ["Gluten-free", "lactose-free"],
    },
    {
      id: 41,
      name: "Halawa Verde",
      price: 105,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_cd24oucd24oucd24.png",
      tags: ["Gluten-free", "keto"],
    },
    {
      id: 42,
      name: "Keto Pistachio Spread Crispy Verde",
      price: 0,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_lmmc2xlmmc2xlmmc.png",
      tags: ["Gluten-free", "Sugar free"],
    },
    {
      id: 43,
      name: "Ganachi light dark chocolate",
      price: 85,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "350 جم",
      ingredients: "خالي قمح وخالي جلوتين وخالي لبن وسويا",
      image: "Gemini_Generated_Image_cy358cy358cy358c.png",
      tags: ["Gluten-free", "Soya free", "milk free", "Wheat free"],
    },
    {
      id: 44,
      name: "Ganachti light dark chocolate",
      price: 180,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "1 كجم",
      ingredients: "",
      image: "Gemini_Generated_Image_gn7d1mgn7d1mgn7d.png",
      tags: ["Gluten-Free", "Egg-Free", "Milk-Free", "Soya-Free", "Vegan - Siam", "Nuts-Free"],
    },
    {
      id: 45,
      name: "Ganachti chocolate hazelnut 1kg",
      price: 180,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "1 كجم",
      ingredients: "خاليه جلوتين وخاليه من الالوان الصناعيه وخاليه من المواد الحافظه",
      image: "Gemini_Generated_Image_lzkiiflzkiiflzki.png",
      tags: ["Gluten-free"],
    },
    {
      id: 46,
      name: "Ganachti chocolate hazelnut 350Gm",
      price: 85,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "350 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_rmwiqnrmwiqnrmwi.png",
      tags: ["Gluten-free"],
    },
    {
      id: 47,
      name: "Classic chocolate bar Hazelnut 90Gm",
      price: 70,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "90 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_up1he6up1he6up1h.png",
      tags: ["Sugar free"],
    },
    {
      id: 48,
      name: "Classic chocolate bar milk 90Gm",
      price: 70,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "90 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_gbxbaogbxbaogbxb.png",
      tags: ["Sugar free"],
    },
    {
      id: 49,
      name: " Classic chocolate bar 90 Gm ",
      price: 70,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "90 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_z4knwmz4knwmz4kn.png",
      tags: ["Sugar free"],
    },
    {
      id: 50,
      name: " Classic chocolate bar 90 Gm ",
      price: 70,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "90 جم",
      ingredients: "",
      image: "Gemini_Generated_Image_ropkz3ropkz3ropk.png",
      tags: ["Sugar free"],
    },
    {
      id: 51,
      name: " Dates powder سكر تمر ",
      price: 55,
      currency: "ج.م",
      category: "البسكويت والحلويات",
      weight: "200 جم",
      ingredients: "تمر مجففف ومطحون ويحتوي علي جميع فوائد التمر من معادن وفيتامينات",
      image: "Gemini_Generated_Image_ai2lr2ai2lr2ai2l.png",
      tags: ["Vegan 100%"],
    },
  ],
};
